### ISSUE TITLE
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:

### ISSUE THREAD

**Issue by dreamitpossible1** [guyuehome/ros2_21_tutorials#1]
rosdep install -i --from-path src --rosdistro eloquent -y
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
learning_tf: Cannot locate rosdep definition for [tf_transformations]
learning_urdf: Cannot locate rosdep definition for [joint_state_publisher_gui]

**Comment by huchunxu** [comment]
ros2_21_tutorials packages are tested in Foxy and Humble. Eloquent maybe not available.



***@***.***
 
From: dreamitpossible1
Date: 2022-09-19 11:06
To: guyuehome/ros2_21_tutorials
CC: Subscribed
Subject: [guyuehome/ros2_21_tutorials] ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies: (Issue #1)
rosdep install -i --from-path src --rosdistro eloquent -y
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
learning_tf: Cannot locate rosdep definition for [tf_transformations]
learning_urdf: Cannot locate rosdep definition for [joint_state_publisher_gui]

**Comment by dreamitpossible1** [comment]
ok，thank
